name: Node.js Build, Versioning and Publish to npm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: Version type to increment (patch, minor, major)
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  version-update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Git Config
        run: |
          git config --global user.name "ci-pipeline"
          git config --global user.email "ci-pipeline@admin.com"
      - name: Update Version
        run: |
          npm version ${{ github.event.inputs.versionType }} -m "Upgrade to %s"
      - name: Push Changes
        run: |
          git push origin main
  npm-publish:
    runs-on: ubuntu-latest
    needs: version-update
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
